apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../apps/base/cluster-cm/configmap.yaml
- gotk-components.yaml
- gotk-sync.yaml
- groups.yaml

patchesStrategicMerge:
  - "./configmap.yaml"