---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: "cilium"
      version: "~1.10.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    hubble:
      ui:
        enabled: true
      relay:
        enabled: true
      bgp:
        announce:
          loadbalancerIP: true
        enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
data:
  config.yaml: |
    peers:
      - peer-address: ${peerIp}
        peer-asn: ${peerAs}
        my-asn: ${myAs:=64512}
    address-pools:
      - name: intern
        protocol: bgp
        addresses:
          - "198.19.${cluster_id}.0/24"