---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "~1.2.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    # global:
    #   imageRegistry: (( concat vars.settings.registry "docker.io"))
    persistence:
      defaultClassReplicaCount: 1 
    csi: 
      kubeletRootDir: "/var/lib/kubelet/"
