---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  install:
    skipCRDs: false
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: "ingress-nginx"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    controller:
      ingressClassByName: true
      ingressClassResource:
        name: intern
        enabled: true
        default: true
    defaultBackend:
      enabled: true