apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-configuration
  namespace: flux-system
data:

  # default value for helm repos
  helm_repo_interval: 1m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glk
  namespace: flux-system
data:
  peerAs: "65542"
  peerIp: "10.124.1.1"
  location: "glk"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glo
  namespace: flux-system
data:
  peerAs: "65541"
  peerIp: "192.168.101.1"
  location: "glo"