---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "~18.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    alertmanager: 
      enabled: false
    grafana:
      enabled: false
    kubeDns:
      enabled: true
    